# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbad7393f0d3d08118ba650611e38f8f7b90c75e97a74cf192a21d8a10fa81e8557992ec7bf7231c27c5fc22fbff4edb2a70ce8bb5d569b08ee4e7039adfbf61

test:
  secret_key_base: 75868d1e100fb285e0e1d4013426d580700b4b04cbb9a7b5db4de1905399e42ccbc695bdbc7cef5c47270d56eb5d0627041f462f1818337d5e37f9c82b0341cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
